name: GitHub Actions Demo

on:
  push:
jobs:
  checkout_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          ls -a
          echo ""
          git branch -a
